- abi.js
- bin.js
- build.js
- package.json
- prebuild.js
- rc.js
- test/rc-test.js
- test/upload-test.js
- upload.js
- util.js
Let me know about adjustments. Upload is tested now. Will obviously squash later.
> Break out all the things

- abi.js
- test/abi-test.js
Closes https://github.com/mafintosh/prebuild/issues/25
> fix version.replace is not a function

- README.md
- build.js
- help.txt
- prebuild.js
- strip.js
- test/strip-test.js
- test/util-test.js
- util.js
The command line flags used for `strip(1)` comes from https://github.com/frida/frida/blob/master/releng/release.py#L77-L82
Closes https://github.com/mafintosh/prebuild/issues/10
cc @oleavr
> add support for --strip + moar tests

- build.js
- gyp.js
- rc.js
- test/gyp-test.js
- test/rc-test.js
- test/util-test.js
- util.js
* make sure prebuild catches --debug from npm environment (npm i --debug)
* if --debug is set, build to build/Debug (util.releaseFolder()) + tests
* pass in --debug to node-gyp if set
* factor out gyp code + tests
Closes https://github.com/mafintosh/prebuild/issues/29
> enable building with --debug

- bin.js
- download.js
- test/download-test.js
> add better error message when no prebuilts are available

- abi.js
- build.js
See commit messages for details.
> Minor enhancements.

- download.js
- test/download-test.js
Also changed the tests a bit. They were testing too much internal details imo. I don't think we should bump major.
> Moar logging during download

- README.md
- bin.js
- help.txt
- rc.js
- test/rc-test.js
> docs + test for --upload-all

- download.js
- util.js
My end goal is to have seamless electron integration, but for now this should enable a more manual process for downloading the desired prebuild
> add --abi option

- .gitignore
- package.json
> audit code with nsp check

- rc.js
so running something like `npm rebuild --target=1.1.3 --abi=48` works
> rc: respect npm env vars "target" and "abi"

- prebuild.js
- test/gypbuild-test.js
Main changes:
- Replace `fs.stat` with `fs.existsSync`
- Use `noop-log` in tests
> Cleanup prebuild script

- bin.js
Fix https://github.com/mafintosh/prebuild/pull/150#discussion_r91936707
> Yarn: Use cwd instead of ~/

- bin.js
- rc.js
makes this possible in your top level package.json:
solves https://github.com/datproject/dat-desktop/issues/74
> add reading config from pkg.config as well

- test/rc-test.js
> add test for rc and external config

- package.json
\cc @ralphtheninja https://github.com/mafintosh/prebuild/pull/146#issuecomment-267758428
> Update contributor list

- package.json
- prebuild.js
> fix: get target from --target=abi

- .gitignore
- gyp.js
- package.json
- test/gypbuild-test.js
Closes https://github.com/mafintosh/prebuild/issues/172
> set gyp.devDir so headers are downloaded correctly

- .travis.yml
- package.json
> Skip nsp on node 4 and 5

- .travis.yml
See https://github.com/prebuild/prebuild/pull/197#discussion_r162833080.
> Tweak conditional nsp to set exit code

- .travis.yml
Closes https://github.com/prebuild/prebuild/issues/200
> travis: add osx

- .travis.yml
- README.md
- package.json
Closes https://github.com/prebuild/prebuild/issues/199
> remove io.js + tweaks

- README.md
- appveyor.yml
- test/integration-test.js
Closes https://github.com/prebuild/prebuild/issues/207
@ralphtheninja
> adds appveyor config

- README.md
- package.json
Some final tweaks before releasing 7.3.0
> add node-webkit to short description + add keyword

- README.md
- build.js
- help.txt
- rc.js
- test/gypbuild-test.js
- test/integration-gyp-test.js
- test/native-module-gyp/package.json
- test/native-module-gyp/prepack.js
- test/rc-test.js
- util.js
This can be used to code sign binaries before they are compressed.
> Added prepack script

- README.md
- help.txt
- rc.js
- test/rc-test.js
- test/upload-test.js
- upload.js
Closes #229 
Related https://github.com/prebuild/prebuild-install/pull/88
> Add --tag-prefix option for github releases

- bin.js
- package.json
- test/rc-test.js
> removed xtend

- appveyor.yml
Closes #237. Also removed some (IMO unnecessary) comments.
> Fix installation of Node.js 11 on AppVeyor

- test/collect-artifacts-test.js
> Test recursively collecting artifacts

- bin.js
Closes https://github.com/prebuild/prebuild/issues/258
> Remove dead code

- .travis.yml
- appveyor.yml
- package.json
Closes https://github.com/prebuild/prebuild/issues/281
> chore: bump node-abi version to 3.0.0

- .npmignore
Relates to https://github.com/prebuild/prebuild/pull/291
> Prevent latest CI config being published to npm

- .github/workflows/ci.yml
- gyp.js
- package.json
- test/gypbuild-test.js
> Update node-gyp to v10

- package.json
- test/integration-cmake-test.js
- test/integration-gyp-test.js
- test/integration-napi-cmake-test.js
- test/integration-napi-gyp-test.js
- test/pack-test.js
> Remove rimraf dependency

- package.json
Breaking changes
- #316
Other changes
- #311
- #315
- #319
- #320
> Release v13.0.0, drops support for Node.js 14
