prebuild/prebuild

rc.js

Default is unset:
```
$ prebuild
rc { target: 'v2.4.0',
arch: 'x64',
platform: 'linux',
_: [ '/usr/local/bin/iojs', '/usr/local/bin/prebuild' ],
compile: undefined,
c: undefined }
```
Using environment variable:
```
$ prebuild_compile=true prebuild
rc { target: 'v2.4.0',
arch: 'x64',
platform: 'linux',
compile: 'true',
_: [ '/usr/local/bin/iojs', '/usr/local/bin/prebuild' ] }
```
Using `--build-from-source` with npm (from leveldown repo):
```
$ npm install --build-from-source
> leveldown@1.3.1-0 install /home/lms/src/leveldb-repos/leveldown
> prebuild --download
rc { target: 'v2.4.0',
arch: 'x64',
platform: 'linux',
compile: true,
_: 
[ '/usr/local/bin/iojs',
'/home/lms/src/leveldb-repos/leveldown/node_modules/.bin/prebuild' ],
download: true,
d: true }
```

move compile property defaults to rc properties

---

bin.js
package.json

On debian systems you may get the `EXDEV` error when moving files between devices, e.g.

use mv instead of fs.rename to get around EXDEV errors

---

bin.js
help.txt

Download from github (default)
```
$ prebuild --download
```
Download from other host (expansion works)
```
$ prebuild --download https://example.com/{name}-v{version}-{abi}-{arch}.tar.gz
```
It's also possible to download based on the `binary` property in package.json

more elaborate downloading

---

bin.js
test/upload-test.js
upload.js

I noticed that prebuild doesn't correctly report how many prebuilts that were actually uploaded, e.g. if we are trying to upload 6, it will report that 6 were uploaded even though they were filtered out. Also, while fixing this, why not also print out the prebuilts that were found?

properly report how many files were uploaded

---

download.js
test/download-test.js
util.js

This allows me to provide all the prebuilds on my build
server instead of having to rebuild the modules
when not neccessary.

Make --download search local prebuilds folder first.

---

package.json
rc.js
test/rc-test.js

This is related to https://github.com/Level/leveldown/issues/228 where `--build-from-source` is passed on from npm to prebuild.
cc @mafintosh @brett19

no-build-from-source -> build-from-source fix

---

bin.js

so `prebuild download --target=5.1.1` builds for `5.1.1` if it has to build. it still defaults to `process.version`

pass --target to build()

---

bin.js

`NVM_IOJS_ORG_MIRROR` and `NVM_NODEJS_ORG_MIRROR` environment variables can mess
up headers, delete them to make sure `node-gyp` uses correct url when downloading headers to `~/.node-gyp`
Closes https://github.com/mafintosh/prebuild/issues/84

delete nvm environment variables

---

README.md
bin.js
help.txt
rc.js
test/rc-test.js

rename the build portion of `--target` to `--prebuild`, so it still looks nice in the prebuildrc.
tests are passing now, i hope though i didn't miss anything.
what do you devs think?

breaking: use .prebuild for prebuild versions

---

README.md
help.txt

We still had the -pb option in help.txt, and --backend wasn't in
README.md. They're consistent now.

Fixed inconsistencies in the help text

---

README.md
abi.js
gypbuild.js
gypinstall.js

Hits when installing new ABI versions. Cause was gypinstall.js not
passing the backend down to gyp, so headers were installed into
$HOME/.node-gyp when using the --backend=node-ninja.
Solution: gypinstall.js passes opts.backend down when calling backend.

Problem: Failed to locate `node.h` and `node_version.h`

---

README.md
help.txt
prebuild.js
rc.js
test/util-test.js
util.js

This is meant to fix https://github.com/mafintosh/prebuild/issues/108
It adds an option for libc argument and LIBC environment variable for use in systems like Alpine linux that use a custom libc.
I was unable to run the test suite on my Mac as it seems it is not currently working for node 6.0 but I am happy to add some tests as advised. 
I have tested it using a scoped package which can be downloaded from NPM as @corbinu/prebuild. 
I also released a version using it and the generated artifacts and travis script can be seen here: https://github.com/corbinu/couchnode

Add option for custom libc

---

gyp.js

node-chakracore uses locally customized node-gyp to support building native
modules. If running on **non-v8** node.js, use the locally installed
node-gyp.
This makes "prebuild --install" work on node-chakracore.

partially support node-chakracore

---

rc.js
test/rc-test.js

Since we don't support prebuilts for Electron we should build from source if the `--runtime=electron` flag is used by `npm`.
It is necessary to build native modules from source to ensure that they are build against the correct Electron headers: http://electron.atom.io/docs/tutorial/using-native-node-modules/
This is especially useful if the module is used inside a Atom package: https://github.com/atom/apm/pull/638

Build from source if used inside electron

---

bin.js
test/util-test.js
util.js

Fixes #132 
This is the way [`electron-builder`](https://github.com/electron-userland/electron-builder) determines if it's installed via Yarn.

Don't default to compile if installed via yarn

---

bin.js

The default log level of `npm` is `warn`.
Hence no log messages of `prebuild` are shown when it is used inside a `npm`-script.

Don't use npm log level

---

rc.js
test/rc-test.js

otherwise `--target=14` will case `node-abi` to fail

make sure .target is always a string

---

package.json
rc.js
test/rc-test.js

This adds Electron 1.5 and 1.6 to supported Targets

Bump node-abi@2.0.0

---

strip.js

Through the `STRIP` environment variable. This is sometimes necessary when
cross-compiling, and is consistent with how gyp allows e.g. `CXX` to be set
to override the C++ compiler used. The name `STRIP` was chosen as autotools
also uses it to override its auto-detection.
Note: I wasn't sure if this should be integrated in the `rc` module or done locally,
so I went for the latter. Please let me know what you'd prefer.

Allow strip program to be overridden

---

pack.js

Hello, the change in this PR offers a quick win to very slightly reduce the output compressed tarball size and therefore very slightly improve tarball download and decompression time.
By way of example, here are the before and after sizes for the latest leveldown binaries:
Before:
```
175256 leveldown-v2.0.0-node-v57-darwin-x64.tar.gz
211712 leveldown-v2.0.0-node-v57-linux-x64.tar.gz
211979 leveldown-v2.0.0-node-v57-win32-ia32.tar.gz
247942 leveldown-v2.0.0-node-v57-win32-x64.tar.gz
```
After:
```
174325 leveldown-v2.0.0-node-v57-darwin-x64.tar.gz
208189 leveldown-v2.0.0-node-v57-linux-x64.tar.gz
211251 leveldown-v2.0.0-node-v57-win32-ia32.tar.gz
246791 leveldown-v2.0.0-node-v57-win32-x64.tar.gz
```

Reduce compressed tarball size by ~1%

---

package.json
rc.js
test/rc-test.js

Hello, here's an initial attempt to integrate *automagic* libc detection via [detect-libc](https://www.npmjs.com/package/detect-libc), as discussed in #149.
It will only set the `libc` option if not already done so via command line or environment variable, and then only when run on a non-glibc Linux to ensure backwards compatibility with the implicit default of glibc.
There were no existing libc related tests so guidance on where best to add these, if any, is most welcome.

Add detection for non-glibc libc on Linux

---

README.md
gypbuild.js
rc.js
test/rc-test.js

Pass through 'format' parameter which is handled by node-gyp configure step
(https://github.com/nodejs/node-gyp/blob/master/lib/configure.js#L216)

add support for 'format' command line parameter

---

gypbuild.js

This variable was added to node 10's build process and is automatically set when building with node 10 but not on older version of node's. Older nodes ignore the flag.
Reference https://github.com/nodejs/node-gyp/issues/1457
Closes https://github.com/prebuild/prebuild/issues/222

Added fix for building node 10

---

gypbuild.js

Same kind of issue as bf45b46aadd80544eb792877eb73ac5781c14b34.
With this and lgeiger/node-abi#51, we can haz prebuilds for Node.js 11.x 🎉

Work around build issue when targeting node 11

---

collect-artifacts.js
package.json

I have a module where I need to distribute a 3rd party DLL along with the .node library, and it has a specific directory structure that needs to be replicated .
Currently collecting artefacts list files in only one level deep. 
This PR changes the file listing to be recursive, allowing any kind of directory structure to be included in the prebuilt package.

Recursively list files in the build directory when collecting artefacts

---

collect-artifacts.js
package.json
test/collect-artifacts-test.js

Hello, I've just run into the breaking change of #238 and later reported as #246.
The proposed fixes in #246 are still breaking changes.
This PR performs a clean revert of the two commits related to #238 and #239 to allow a non-breaking v8.2.x release without preventing a second attempt in a later breaking v9.0.0 release to include this feature (e.g. by cherry-picking the commits back in again).

Revert recursive behaviour to allow non-breaking v8.2.x release

---

package.json

Some change between `cmake-js` 5.2.0 and 5.3.0 broke our AppVeyor tests ([logs](https://ci.appveyor.com/project/mathiask88/prebuild/builds/25930825/job/6tciae0pajf6a36r)), as well as locally on my machine. See https://github.com/cmake-js/cmake-js/issues/186.

Pin cmake-js to ~5.2.0 to fix building on Windows

---

bin.js

Just a change to fix the Branding™ here that I couldn't overlook any longer

renamed mentions of "Github" to "GitHub"

---

.travis.yml
appveyor.yml
bin.js
pack.js
package.json
prebuild.js

I intend for this to be included in a 9.1.0 release. Upgraded all dependencies except for `node-gyp` (deserves more scrutiny and probably a major bump here) and `cmake-js` (see #254).

Upgrade dependencies and add node 12 to CI

---

gyp.js
gypbuild.js
package.json
test/gypbuild-test.js

Adapted from `prebuildify`. Closes #249.

Fix node-gyp cache conflict between node and electron

---

package.json

I didn't find anyone talking about this in the issues, so maybe this PR will spark some conversation.
I didn't personally run into issues while doing this in my project:
```
cd node_modules/prebuild && npm i node-gyp@5
```
Breaking changes in 5.x: https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#v500-2019-06-13
Breaking changes in 4.x: https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#v400-2019-04-24
---
Any chance the version of `node-gyp` could be configurable?

Update node-gyp to 6.x

---

bin.js
package.json

A small change to fix #245, based on the [last comment](https://github.com/prebuild/prebuild/issues/245#issuecomment-471728217) there. This adds an extra dependency on glob, but it's already a transitive dependency anyway.
Rather than do just one level (all that's strictly necessary to make namespaced packages work) this is recursive, so it flattens the tree and uploads every file in `./prebuilds`. Happy to debate that, but I think it more accurately matches the documented behaviour of `upload-all`:
> upload all files from ./prebuilds folder to github

Support namespaced packages in upload-all

---

README.md
package.json

The Node.js core technology supporting the implementation on native add-ons previously known as **N-API** has been renamed to **Node-API** to make the name more appropriate and descriptive. This PR updates the project's documentation to reflect this change.

Update documentation for Node-API

---

package.json
rc.js

Hello, this is the "sibling" change for the approved https://github.com/prebuild/prebuild-install/pull/166 and should also be considered `semver-patch` as `prebuild` currently requires Node.js >= 10.
The change in this PR can be published independently of the `prebuild-install` change.

Upgrade to version 2 of detect-libc

---

prebuild.js
strip.js
test/strip-test.js

As I was trying to change [the `--include-regex` parameter to include multiple files](https://github.com/desktop/desktop-trampoline/blob/8b38cd56a192f423b0e89121641f8526b86ed627/package.json#L18-L20) in the prebuild bundle, while preserving the `--strip` parameter, I noticed `strip` wasn't prepared to receive an array of files (which is what `collect` generates, even when it's only 1 file). In the end, the `spawn` function received an args parameter that looked like this: `[ [ 'build/Release/desktop-trampoline' ], '-Sx' ]`
This PR changes `strip` to accept multiple files, and processes those files sequentially.

Support stripping multiple files

---

.github/workflows/ci.yml
README.md
pack.js
package.json
test/gypbuild-test.js
test/integration-cmake-test.js
test/integration-gyp-test.js
test/integration-napi-cmake-test.js
test/integration-napi-gyp-test.js
test/native-module-gyp/binding.gyp
test/native-module-napi-cmake/CMakeLists.txt
test/native-module-napi-gyp/binding.gyp

This is a semver major change, please see https://github.com/prebuild/prebuild/issues/286 for discussion and details.
It also:
- Upgrades all dependencies to their most recent version that still supports Node.js 14.
- Synchronises the `engines.node` property with that of the latest `node-gyp` we're upgrading to.
- Ensures all tests run on all platforms as I noticed some of the cmake-js tests were optionally being skipped.
- Ensures the `native-module-napi-cmake` test includes the CMake config required for use with Node-API.
- Removes the no-longer-required `mkdirp` dependency as Node.js has provided this feature since version 10.
- Removes unused CI "badges" from the readme
Additions based on feedback:
- Defines deployment target in test fixtures (rather than CI config) so tests can be …

Add support for Node.js 20, drop support for Node.js 10 and 12

---

package.json

- https://github.com/prebuild/prebuild/pull/291
- https://github.com/prebuild/prebuild/pull/304

Release v12.0.0, drops support for Node.js 10 and 12

---

README.md
help.txt
rc.js
test/rc-test.js
test/upload-test.js
upload.js

This is useful if you want to prevent a newly-created release being labelled by GitHub as "latest". The GitHub UI provides a checkbox to change this status later.
This is a simpler version of https://github.com/prebuild/prebuild/pull/127 that doesn't attempt to implement any semver logic, only the `--prerelease` option and associated tests, which will add the `prerelease` property to the underlying [GitHub API call](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release).
Fixes https://github.com/prebuild/prebuild/issues/126

Add prerelease option

---

gypbuild.js
test/gypbuild-test.js

When building for a different architecture using node-gyp, the arch option should be used. Using target_arch populates the variable usable in the binding.gyp file, but node-gyp will still do a build with the system's architecture.

Use arch instead of target_arch

---

.github/workflows/ci.yml

There's an intermittent problem with the specific combo of npm 10 + Node.js 18 + 32-bit Windows where running `npm install` opens thousands of network connections, leading to resource starvation and a process crash.
This PR pins the 32-bit Windows Node.js 18 CI job to the most recent version that ships with npm 9, which is the same approach as I'm using in sharp - see https://github.com/lovell/sharp/commit/420e0822b4631aa8187af7600d340180aeb37afe

CI: Pin Node.js 18 on 32-bit Windows to use npm 9

---

cmakebuild.js

This fixes #324 - I've tested on a Windows x86_64 and on my MacBook M3 (arm64).
I considered adding it here as well: https://github.com/prebuild/prebuild/blob/af905c75861d6692d63ef3cc386a7682b41a0941/util.js#L20
But it seems the only code (currently) calling this of that util is disabled on Windows: https://github.com/prebuild/prebuild/blob/af905c75861d6692d63ef3cc386a7682b41a0941/strip.js#L6

Update cmakebuild.js to spawn with `shell: true`
